



#druid连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/javadb
      username: root
      password: shao778851
      driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis -彻底抛弃mybatis-config.xml
#mapper.xml的位置  setting的配置 别名配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml    #指定xml文件的位置
  type-aliases-package: com.atguigu.pojo
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰映射
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl